[colors.bright]
black = "0x676767"
blue = "0xa6aaf1"
cyan = "0x5ffdff"
green = "0x57e690"
magenta = "0xe07de0"
red = "0xdc7974"
white = "0xfeffff"
yellow = "0xece100"

[colors.cursor]
cursor = "0xfefffe"
text = "0x000000"

[colors.normal]
black = "0x000000"
blue = "0x4c0be3"
cyan = "0x1fffff"
green = "0x00c200"
magenta = "0x94167f"
red = "0xb43c29"
white = "0xc7c7c7"
yellow = "0xf9ac53"

[colors.primary]
background = "0x14191e"
foreground = "0xdbdbdb"

[colors.selection]
background = "0xb3d7ff"
text = "0x000000"
