import = ["/home/$USER/.config/alacritty/themes/themes/vapor.toml"]

[bell]
animation = "EaseOutCirc"
color = "#4C0BE2"
duration = 200

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[cursor]
blink_interval = 350
blink_timeout = 0
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 16.0

[font.bold]
family = "monospace"

[font.glyph_offset]
x = 0
y = -2

[font.normal]
family = "Liberation Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000

[window]
dynamic_title = true
opacity = 0.95

[window.class]
general = "Alacritty"
instance = "Alacritty"
